const e=JSON.parse('{"key":"v-3e835c00","path":"/pages/9003d665/","title":"深入理解 Java 异常","lang":"zh-CN","frontmatter":{"title":"深入理解 Java 异常","date":"2019-05-06T15:02:02.000Z","order":"08","permalink":"/pages/9003d665/","category":["Java","JavaCore","基础特性"],"tag":["Java","JavaCore","异常"],"description":"深入理解 Java 异常 img 异常框架 Throwable **Throwable 是 Java 语言中所有错误（Error）和异常（Exception）的超类。**在 Java 中只有 Throwable 类型的实例才可以被抛出（throw）或者捕获（catch），它是异常处理机制的基本组成类型。","head":[["meta",{"property":"og:url","content":"https://dunwu.github.io/waterdrop/waterdrop/pages/9003d665/"}],["meta",{"property":"og:site_name","content":"钝悟"}],["meta",{"property":"og:title","content":"深入理解 Java 异常"}],["meta",{"property":"og:description","content":"深入理解 Java 异常 img 异常框架 Throwable **Throwable 是 Java 语言中所有错误（Error）和异常（Exception）的超类。**在 Java 中只有 Throwable 类型的实例才可以被抛出（throw）或者捕获（catch），它是异常处理机制的基本组成类型。"}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2025-09-13T09:10:08.000Z"}],["meta",{"property":"article:author","content":"钝悟"}],["meta",{"property":"article:tag","content":"Java"}],["meta",{"property":"article:tag","content":"JavaCore"}],["meta",{"property":"article:tag","content":"异常"}],["meta",{"property":"article:published_time","content":"2019-05-06T15:02:02.000Z"}],["meta",{"property":"article:modified_time","content":"2025-09-13T09:10:08.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"深入理解 Java 异常\\",\\"image\\":[\\"\\"],\\"datePublished\\":\\"2019-05-06T15:02:02.000Z\\",\\"dateModified\\":\\"2025-09-13T09:10:08.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"钝悟\\",\\"url\\":\\"https://dunwu.github.io/waterdrop\\"}]}"]]},"headers":[{"level":2,"title":"异常框架","slug":"异常框架","link":"#异常框架","children":[{"level":3,"title":"Throwable","slug":"throwable","link":"#throwable","children":[]},{"level":3,"title":"Error","slug":"error","link":"#error","children":[]},{"level":3,"title":"Exception","slug":"exception","link":"#exception","children":[]},{"level":3,"title":"RuntimeException","slug":"runtimeexception","link":"#runtimeexception","children":[]}]},{"level":2,"title":"自定义异常","slug":"自定义异常","link":"#自定义异常","children":[]},{"level":2,"title":"抛出异常","slug":"抛出异常","link":"#抛出异常","children":[]},{"level":2,"title":"捕获异常","slug":"捕获异常","link":"#捕获异常","children":[]},{"level":2,"title":"异常链","slug":"异常链","link":"#异常链","children":[]},{"level":2,"title":"异常注意事项","slug":"异常注意事项","link":"#异常注意事项","children":[{"level":3,"title":"finally 覆盖异常","slug":"finally-覆盖异常","link":"#finally-覆盖异常","children":[]},{"level":3,"title":"覆盖抛出异常的方法","slug":"覆盖抛出异常的方法","link":"#覆盖抛出异常的方法","children":[]},{"level":3,"title":"异常和线程","slug":"异常和线程","link":"#异常和线程","children":[]}]},{"level":2,"title":"最佳实践","slug":"最佳实践","link":"#最佳实践","children":[]},{"level":2,"title":"参考资料","slug":"参考资料","link":"#参考资料","children":[]}],"git":{"createdTime":1743948422000,"updatedTime":1757754608000,"contributors":[{"name":"dunwu","email":"forbreak@163.com","commits":2}]},"readingTime":{"minutes":11.81,"words":3544},"filePathRelative":"01.Java/01.JavaCore/01.基础特性/Java_异常.md","localizedDate":"2019年5月6日","excerpt":"<h1> 深入理解 Java 异常</h1>\\n<figure><img src=\\"https://raw.githubusercontent.com/dunwu/images/master/snap/1553752019030.png\\" alt=\\"img\\" tabindex=\\"0\\" loading=\\"lazy\\"><figcaption>img</figcaption></figure>\\n<h2> 异常框架</h2>\\n<h3> Throwable</h3>\\n<p>**<code>Throwable</code> 是 Java 语言中所有错误（<code>Error</code>）和异常（<code>Exception</code>）的超类。**在 Java 中只有 <code>Throwable</code> 类型的实例才可以被抛出（<code>throw</code>）或者捕获（<code>catch</code>），它是异常处理机制的基本组成类型。</p>","autoDesc":true}');export{e as data};
